#!/usr/bin/env python
import argparse
# from lhe2sqlite import convert
import lhe2sqlite

if __name__ == '__main__':
    desc = 'Converts a LesHouchesEvents formatted file to a sqlite database file'
    parser = argparse.ArgumentParser('convertlhe2sql', description=desc)
    parser.add_argument('filein', metavar='input.lhe[.gz]')
    parser.add_argument('fileout', metavar='output.sqlite3', nargs='?')
    args = parser.parse_args()
    lhe2sqlite.convert(args.filein, args.fileout)
